### ISSUE TITLE
More stringent password requierments

### ISSUE THREAD

**Issue by PazZaitGivon** [UCSB-CS56-Projects/cs56-utilities-password-generator#11]
Make it so that people can make categories of characters and require that something from each category appears a specified number of times in the password. This is often a requirement for passwords.

~Estimated 200 points

**Comment by arda-** [comment]
Vince and I plan to implement the following enhancements to the current program that will create better control of the password generation recipe:

A check box for each of the following areas, so that the user may include or exclude any of the following types of characters, and text-box interfaces to set the range of characters they want in each type:
* uppercase, min/max
* lowercase, min/max
* digits, min/max
* special chars, min/max, default set or user's set

Min/max 

This is more of an above-and-beyond improvement to the program, as it depends on many current issues:
* #4 - restructuring and refactoring of the build.xml, 
* #9 - making the GUI decent
* #13 - the special chars not actually affecting output bug
* #14 - JUnit tests for the existing code.

proposed **150 points** for refactoring the constructors, setters and getters to accommodate the new features, and **100 points** for the new corresponding unit tests (250 total points)

proposed label: enchancement

**Comment by PazZaitGivon** [comment]
looks and works great but still buggy in that if min and max are the same or min is greater than max it just throws a bunch of exceptions and does nothing. 50 points proposed to fix this with appropriate error messages in the gui and for the 4 just make it exactly that ammount of said charachters

**Comment by arda-** [comment]
I think Vince might have addressed this in his Issues for next year part form lab08, though correct me if I'm wrong!

**Comment by PazZaitGivon** [comment]
Your right! but he left out a bit about making the exact amount if min and max are equal. Good job on this guys!
