### ISSUE TITLE
Restructure Files

### ISSUE THREAD

**Issue by jcneally** [UCSB-CS56-Projects/cs56-utilities-password-generator#4]
Restructure the files to the standard for CS56 projects.

~estimated 50 points

**Comment by arda-** [comment]
The above reference from a commit is accidental.

**Comment by arda-** [comment]
Planned improvements to the current GUI:
* Reformat layout of text and text boxes (2-column format of "prompt: [entry in text box]" is more appropriate)
* Add minimum/maximum window size (So no clipping of content occurs if window is resized)

**Comment by arda-** [comment]
Improving organization and build.xml is still currently a relevant issue;


depends #14 


improve descriptions of ant targets (i.e. run vs. run 2) in build.xml - 25 points

**Comment by arda-** [comment]
See Issue #22 for the above-and-beyond implementation for the solution to this issue, which does the following:
* If the user does not have the Junit package on their machine, then gracefully exit and let the user know that they need to specify a JUnit package location.
* installs Junit if necessary
* soft-codes the location of the user's JUnit package so that it will compile and run at locations other than CSIL.

**Comment by PazZaitGivon** [comment]
this issue seems to have migrated to issue 22 so closing this one
